[package]
name = "spinner"
version = "0.1.0"
authors = ["XxMicrowavexX <76092869+XxMicrowavexX@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
